### ISSUE TITLE
Running neftSample app (Bugs!)

### ISSUE THREAD

**Issue by Randore** [Neft-io/neft#97]
**neft create MyApp
cd MyApp
neft build browser
neft run node**

--------
Issue: After running 'neft build browser', if I run the command 'neft run browser' it open localhost but fails to load the page (error page).

Issue: If we run 'neft run node' it parses and asks us to open port at localhost:3000 which i think is not a good solution.

Issue: For webapp are we following semantics? 
![neft-text](https://cloud.githubusercontent.com/assets/443526/16068746/19dab352-32e6-11e6-89c9-045accd77689.png)

I think a good solution would be; when I run the command "node run neft" it should parse and show it in localhost. And add a watcher param to check for local changes and compile automatically.

Example:
"node run neft:w (or) neft run --watch"

**Comment by KrysKruk** [comment]
Hi! Thanks for bug report.

1. App runs Node server on `localhost:3000` by default which can be changed in `package.json` file. Browser bundle right now requires server to download bundle and static resource files. ios and android works offline. Any ideas here?
2. Generated HTML is a mess, because it's creating automatically by the renderer. The same renderer generates ios/android/webgl views, so semantics are not so important; browser HTML is mostly performance focused so animations should works very fast. For GoogleBot or any other kind of bots (manual requests to the server as well) you will get your HTML from the `views/`.
3. You can use `--watch` argument. e.g. `neft build browser --watch` should works fine. Check [Tour](https://github.com/Neft-io/neft/wiki/First-Application---Tour#run-in-a-browser) on wiki.

Again. Thanks for feedback. It's so important for the project to get informations from developers. In any other issues or ideas, please feel free to discuss/create issues etc.

**Comment by Randore** [comment]
@KrysKruk awesome
